version: "3"

services:
  demo_postgres14:
    image: postgres:14
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - 5433:5432 # 외부 포트 : 내부 포트(어지간하면 수정 X)
    restart: on-failure
    volumes:
      - stick_volume_demo_postgres14:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro

volumes:
  stick_volume_demo_postgres14: